### ISSUE TITLE
"pyg update" data isn't dynamic

### ISSUE THREAD

**Issue by fdev31** [rubik/pyg#87] opened 2011-06-20 08:04 UTC
After in a run of `pyg update`, it will ask to upgrade packages that were already upgraded:

```
% pyg upgrade
[...]

A new release is avaiable for RunSnakeRun: 2.0.1 (old 2.0.1b6)
Do you want to upgrade? (y/[n]) y
Removing RunSnakeRun old version
Upgrading RunSnakeRun to 2.0.1
        Installing RunSnakeRun-2.0.1.tar.gz...
            Installing RunSnakeRun-2.0.1.tar.gz from http://pypi.python.org/packages/source/R/RunSnakeRun/RunSnakeRun-2.0.1.tar.gz
            Running setup.py egg_info for RunSnakeRun-2.0.1.tar.gz
            Running setup.py install for RunSnakeRun-2.0.1.tar.gz
            Installing dependencies...
Installing SquareMap >= 1.0.1b3 (from RunSnakeRun-2.0.1.tar.gz)
        Looking for SquareMap releases on PyPI
        Best match: SquareMap==1.0.1b3
        Downloading SquareMap [100% - 7.2 Kb] 
        Checking md5 sum
        Running setup.py egg_info for SquareMap
        Running setup.py install for SquareMap
        SquareMap installed successfully
Finished installing dependencies for RunSnakeRun-2.0.1.tar.gz
RunSnakeRun-2.0.1.tar.gz installed successfully
A new release is avaiable for SQLAlchemy: 0.7.1 (old 0.6.6)
Do you want to upgrade? (y/[n]) n$
Do you want to upgrade? (y/[n]) 
SQLAlchemy has not been upgraded
A new release is avaiable for SQLObject: 0.15.1 (old 0.13.0)
Do you want to upgrade? (y/[n]) 
SQLObject has not been upgraded
A new release is avaiable for South: 0.7.3 (old 0.7.2)
Do you want to upgrade? (y/[n]) 
South has not been upgraded
A new release is avaiable for SquareMap: 1.0.1b3 (old 1.0.1b2)
Do you want to upgrade? (y/[n]) 
```

You can see that SquareMap have already been upgraded...

**Comment by fdev31** [comment] 2011-06-20 09:36
Hum... after interrupting this "upgrade" command I don't have setuptools anymore on my system... :/

**Comment by fdev31** [comment] 2011-06-20 09:46
I think I should fill a new bug report, but "pyg upgrade" just removed my /usr/local/lib/python2.7/{site,dist}-packages !! :(((
This is critical...

**Comment by rubik** [comment] 2011-06-20 14:04
Argh, that is really critical!! :(
I think the problem is in the Uninstaller, where we add dist.location to guesses:
https://github.com/rubik/pyg/blob/master/pyg/inst.py#L214

For some packages, dist.location refers to the package's directory, for others to the whole site-packages! We should really fix that.

**Comment by rubik** [comment] 2011-06-20 14:17
Can you commit that? I'm not at home and I cannot fix it.

**Comment by fdev31** [comment] 2011-06-20 14:31
What should I commit ? I don't understand why this code is doing two different things regarding the python version... Makes sense to only use the "pre 2.7" feature but that code is probably here for some good reason, don't you think ? :P

**Comment by rubik** [comment] 2011-06-23 17:33
> I think I should fill a new bug report, but "pyg upgrade" just removed my /usr/local/lib/python2.7/{site,dist}-packages !! :(((
> This is critical...

I hope that didn't cause troubles for you! Sorry! :((

Now I'm looking for a clean solution...

**Comment by fdev31** [comment] 2011-06-23 21:01
Heh, nothing too difficult to undo for now, since I have multiple versions of python installed on this computer that reduced the scale of the problem :) Thanks for asking btw...

**Comment by fdev31** [comment] 2011-07-05 20:56
Now the removal part is fixed (until next bug ;) so this is just about not installing some packages even if not necessary...

**Comment by rubik** [comment] 2011-07-06 07:45
Pyg update relies on pkg_resources.working_set, to gather packages in the environment and their information.

**Comment by fdev31** [comment] 2011-07-06 10:13
```
        for dist in self.working_set:
```

This is computed once... I think we should do a real set, and then remove packages from it as soon as they are installed...
I'm not sure of the current implementation, I would have to study the code a little.
Btw, I don't think it's necessary for the 0.7 version :)

**Comment by rubik** [comment] 2011-07-14 18:35
Ok, so I close it now! :)

EDIT: All tests are passing!! :)

**Closed as completed by rubik** 2011-07-14 18:35 UTC
Labels: enhancement, bug, important

**Comment by fdev31** [comment] 2011-07-15 09:34
I think we should manage some test around that, ensuring dependencies are
not installed again and again...

Le 6 juil. 2011 09:45, "rubik" <
reply@reply.github.com> a
crit :

Pyg update relies on pkg_resources.working_set, to gather packages in the
environment and their information.

##
